fighters = [
    {"name":"Devon Duffee","type":"fighter","age":19,"promotion":"Independent","weight_class":"Light Heavyweight","reputation":48,"potential":97,"style":"Striker","status":"Prospect","country":"USA","city":"Detroit"},
    {"name":"Malik Brunson","type":"fighter","age":18,"promotion":"Independent","weight_class":"Middleweight","reputation":8,"potential":72,"style":"Balanced","status":"Amateur","country":"USA","city":"Detroit"},

    {"name":"Jon Jones","type":"fighter","age":39,"promotion":"UFC","weight_class":"Heavyweight","reputation":99,"potential":100,"style":"Mixed","status":"Legend","country":"USA","city":"Albuquerque"},
    {"name":"Conor McGregor","type":"fighter","age":37,"promotion":"UFC","weight_class":"Lightweight","reputation":100,"potential":100,"style":"Striker","status":"Superstar","country":"Ireland","city":"Dublin"},
    {"name":"Islam Makhachev","type":"fighter","age":34,"promotion":"UFC","weight_class":"Lightweight","reputation":95,"potential":96,"style":"Wrestler","status":"Champion","country":"Russia","city":"Makhachkala"},
    {"name":"Alex Pereira","type":"fighter","age":38,"promotion":"UFC","weight_class":"Light Heavyweight","reputation":93,"potential":95,"style":"Kickboxer","status":"Champion","country":"Brazil","city":"Sao Paulo"},
    {"name":"Sean O'Malley","type":"fighter","age":31,"promotion":"UFC","weight_class":"Bantamweight","reputation":91,"potential":94,"style":"Striker","status":"Contender","country":"USA","city":"Phoenix"},
    {"name":"Khamzat Chimaev","type":"fighter","age":32,"promotion":"UFC","weight_class":"Middleweight","reputation":90,"potential":96,"style":"Wrestler","status":"Contender","country":"UAE","city":"Abu Dhabi"},
    {"name":"Ilia Topuria","type":"fighter","age":29,"promotion":"UFC","weight_class":"Featherweight","reputation":89,"potential":97,"style":"Boxer","status":"Champion","country":"Spain","city":"Alicante"},
    {"name":"Leon Edwards","type":"fighter","age":34,"promotion":"UFC","weight_class":"Welterweight","reputation":90,"potential":91,"style":"Kickboxer","status":"Champion","country":"UK","city":"Birmingham"},
    {"name":"Belal Muhammad","type":"fighter","age":37,"promotion":"UFC","weight_class":"Welterweight","reputation":84,"potential":85,"style":"Pressure","status":"Champion","country":"USA","city":"Chicago"},
    {"name":"Tom Aspinall","type":"fighter","age":33,"promotion":"UFC","weight_class":"Heavyweight","reputation":88,"potential":95,"style":"Mixed","status":"Champion","country":"UK","city":"Manchester"},
    {"name":"Dricus Du Plessis","type":"fighter","age":33,"promotion":"UFC","weight_class":"Middleweight","reputation":87,"potential":91,"style":"Brawler","status":"Champion","country":"South Africa","city":"Pretoria"},
    {"name":"Max Holloway","type":"fighter","age":35,"promotion":"UFC","weight_class":"Featherweight","reputation":93,"potential":94,"style":"Volume Striker","status":"Legend","country":"USA","city":"Hawaii"},
    {"name":"Charles Oliveira","type":"fighter","age":36,"promotion":"UFC","weight_class":"Lightweight","reputation":94,"potential":94,"style":"Submission","status":"Contender","country":"Brazil","city":"Sao Paulo"},
    {"name":"Dustin Poirier","type":"fighter","age":37,"promotion":"UFC","weight_class":"Lightweight","reputation":95,"potential":92,"style":"Boxer","status":"Legend","country":"USA","city":"Lafayette"},
    {"name":"Justin Gaethje","type":"fighter","age":37,"promotion":"UFC","weight_class":"Lightweight","reputation":93,"potential":91,"style":"Brawler","status":"Contender","country":"USA","city":"Denver"},
    {"name":"Michael Chandler","type":"fighter","age":39,"promotion":"UFC","weight_class":"Lightweight","reputation":89,"potential":87,"style":"Wrestler","status":"Veteran","country":"USA","city":"Nashville"},
    {"name":"Paddy Pimblett","type":"fighter","age":31,"promotion":"UFC","weight_class":"Lightweight","reputation":82,"potential":90,"style":"Grappler","status":"Rising Star","country":"UK","city":"Liverpool"},
    {"name":"Shavkat Rakhmonov","type":"fighter","age":31,"promotion":"UFC","weight_class":"Welterweight","reputation":88,"potential":97,"style":"Mixed","status":"Contender","country":"Kazakhstan","city":"Aktobe"},
    {"name":"Bo Nickal","type":"fighter","age":29,"promotion":"UFC","weight_class":"Middleweight","reputation":80,"potential":96,"style":"Wrestler","status":"Prospect","country":"USA","city":"Pennsylvania"},
    {"name":"Jiri Prochazka","type":"fighter","age":34,"promotion":"UFC","weight_class":"Light Heavyweight","reputation":90,"potential":93,"style":"Wild Striker","status":"Contender","country":"Czech Republic","city":"Brno"},
    {"name":"Israel Adesanya","type":"fighter","age":37,"promotion":"UFC","weight_class":"Middleweight","reputation":97,"potential":97,"style":"Kickboxer","status":"Legend","country":"New Zealand","city":"Auckland"},
    {"name":"Robert Whittaker","type":"fighter","age":35,"promotion":"UFC","weight_class":"Middleweight","reputation":92,"potential":91,"style":"Mixed","status":"Veteran","country":"Australia","city":"Sydney"},
    {"name":"Cory Sandhagen","type":"fighter","age":34,"promotion":"UFC","weight_class":"Bantamweight","reputation":86,"potential":90,"style":"Technical Striker","status":"Contender","country":"USA","city":"Denver"}
]
