fighters = [
    {
        "name": "Conor McGregor",
        "nickname": "The Notorious",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Lightweight",
        "country": "Ireland",
        "city": "Dublin",
        "followers": 47000000,
        "reputation": 99,
        "prime": False,
        "active": True
    },
    {
        "name": "Jon Jones",
        "nickname": "Bones",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Heavyweight",
        "country": "USA",
        "city": "Albuquerque",
        "followers": 9000000,
        "reputation": 98,
        "prime": False,
        "active": True
    },
    {
        "name": "Alex Pereira",
        "nickname": "Poatan",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Light Heavyweight",
        "country": "Brazil",
        "city": "São Paulo",
        "followers": 6200000,
        "reputation": 95,
        "prime": True,
        "active": True
    },
    {
        "name": "Sean O'Malley",
        "nickname": "Suga",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Bantamweight",
        "country": "USA",
        "city": "Phoenix",
        "followers": 4300000,
        "reputation": 92,
        "prime": True,
        "active": True
    },
    {
        "name": "Islam Makhachev",
        "nickname": "The Eagle 2.0",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Lightweight",
        "country": "Russia",
        "city": "Makhachkala",
        "followers": 9800000,
        "reputation": 96,
        "prime": True,
        "active": True
    },
    {
        "name": "Khamzat Chimaev",
        "nickname": "Borz",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Middleweight",
        "country": "Sweden",
        "city": "Stockholm",
        "followers": 7400000,
        "reputation": 94,
        "prime": True,
        "active": True
    },
    {
        "name": "Ilia Topuria",
        "nickname": "El Matador",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Featherweight",
        "country": "Spain",
        "city": "Alicante",
        "followers": 3000000,
        "reputation": 91,
        "prime": True,
        "active": True
    },
    {
        "name": "Leon Edwards",
        "nickname": "Rocky",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Welterweight",
        "country": "England",
        "city": "Birmingham",
        "followers": 2200000,
        "reputation": 88,
        "prime": True,
        "active": True
    },
    {
        "name": "Dricus Du Plessis",
        "nickname": "Stillknocks",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Middleweight",
        "country": "South Africa",
        "city": "Pretoria",
        "followers": 1800000,
        "reputation": 87,
        "prime": True,
        "active": True
    },
    {
        "name": "Max Holloway",
        "nickname": "Blessed",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Featherweight",
        "country": "USA",
        "city": "Honolulu",
        "followers": 4200000,
        "reputation": 94,
        "prime": False,
        "active": True
    },
    {
        "name": "Dustin Poirier",
        "nickname": "The Diamond",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Lightweight",
        "country": "USA",
        "city": "Lafayette",
        "followers": 5100000,
        "reputation": 95,
        "prime": False,
        "active": True
    },
    {
        "name": "Justin Gaethje",
        "nickname": "The Highlight",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Lightweight",
        "country": "USA",
        "city": "Denver",
        "followers": 2600000,
        "reputation": 91,
        "prime": False,
        "active": True
    },
    {
        "name": "Charles Oliveira",
        "nickname": "Do Bronx",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Lightweight",
        "country": "Brazil",
        "city": "São Paulo",
        "followers": 9000000,
        "reputation": 95,
        "prime": True,
        "active": True
    },
    {
        "name": "Tom Aspinall",
        "nickname": "Honey Badger",
        "sport": "MMA",
        "organization": "UFC",
        "division": "Heavyweight",
        "country": "England",
        "city": "Manchester",
        "followers": 1800000,
        "reputation": 88,
        "prime": True,
        "active": True
    },
    {
        "name": "Francis Ngannou",
        "nickname": "The Predator",
        "sport": "MMA",
        "organization": "PFL",
        "division": "Heavyweight",
        "country": "Cameroon",
        "city": "Batié",
        "followers": 7000000,
        "reputation": 96,
        "prime": True,
        "active": True
    },
    {
        "name": "Canelo Alvarez",
        "nickname": "Canelo",
        "sport": "Boxing",
        "organization": "WBC",
        "division": "Super Middleweight",
        "country": "Mexico",
        "city": "Guadalajara",
        "followers": 19000000,
        "reputation": 98,
        "prime": False,
        "active": True
    },
    {
        "name": "Gervonta Davis",
        "nickname": "Tank",
        "sport": "Boxing",
        "organization": "WBA",
        "division": "Lightweight",
        "country": "USA",
        "city": "Baltimore",
        "followers": 6200000,
        "reputation": 94,
        "prime": True,
        "active": True
    },
    {
        "name": "Tyson Fury",
        "nickname": "The Gypsy King",
        "sport": "Boxing",
        "organization": "WBC",
        "division": "Heavyweight",
        "country": "England",
        "city": "Manchester",
        "followers": 9500000,
        "reputation": 96,
        "prime": False,
        "active": True
    },
    {
        "name": "Deontay Wilder",
        "nickname": "The Bronze Bomber",
        "sport": "Boxing",
        "organization": "WBC",
        "division": "Heavyweight",
        "country": "USA",
        "city": "Tuscaloosa",
        "followers": 3400000,
        "reputation": 91,
        "prime": False,
        "active": True
    },
    {
        "name": "Terence Crawford",
        "nickname": "Bud",
        "sport": "Boxing",
        "organization": "WBO",
        "division": "Welterweight",
        "country": "USA",
        "city": "Omaha",
        "followers": 1700000,
        "reputation": 94,
        "prime": False,
        "active": True
    }
]
